// Server-side Nielsen client — downloads pre-aggregated JSON from S3.
// Generated by ~/SaSMaster/scripts/portal-nielsen-summary.js (daily 6AM cron).
// Falls back to realistic statics if S3 is unavailable.

import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3'

const BUCKET = process.env.S3_BUCKET    ?? 'sasmaster-2026'
const S3_KEY = 'portal/nielsen-summary.json'
const REGION = process.env.AWS_REGION   ?? 'us-east-1'

let cache: { data: NielsenSummary; expiresAt: number } | null = null

interface MarketMetrics {
  totalViewers: number; totalViewersDelta: number
  share: number;        shareDelta: number
  reach: number;        reachDelta: number
  avgMinAud: number;    avgMinAudDelta: number
  isRealTime: boolean
}

interface TrendPoint { date: string; viewers: number; viewersPriorYear: number }

interface NielsenSummary {
  market:    MarketMetrics
  trend30d:  TrendPoint[]
  updatedAt: string
  source:    string
}

function getS3Client() {
  return new S3Client({
    region: REGION,
    credentials: {
      accessKeyId:     process.env.AWS_ACCESS_KEY_ID!,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
    },
  })
}

async function streamToString(stream: NodeJS.ReadableStream): Promise<string> {
  const chunks: Uint8Array[] = []
  for await (const chunk of stream) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : (chunk as Uint8Array))
  }
  return Buffer.concat(chunks).toString('utf8')
}

async function fetchFromS3(): Promise<NielsenSummary> {
  const s3  = getS3Client()
  const obj = await s3.send(new GetObjectCommand({ Bucket: BUCKET, Key: S3_KEY }))
  const raw = await streamToString(obj.Body as NodeJS.ReadableStream)
  return JSON.parse(raw) as NielsenSummary
}

function fallbackSummary(): NielsenSummary {
  const today = new Date()
  const trend: TrendPoint[] = Array.from({ length: 30 }, (_, i) => {
    const date = new Date(today)
    date.setDate(today.getDate() - (29 - i))
    const base = 300_000_000 + Math.sin(i * 0.4) * 20_000_000 + i * 500_000
    return { date: date.toISOString().split('T')[0]!, viewers: Math.round(base), viewersPriorYear: Math.round(base * 0.94) }
  })
  return {
    market: {
      totalViewers: 311_200_000, totalViewersDelta: 0.8,
      share: 12.4,               shareDelta: -1.2,
      reach: 89_700_000,         reachDelta: 2.3,
      avgMinAud: 4_200_000,      avgMinAudDelta: 3.1,
      isRealTime: false,
    },
    trend30d:  trend,
    updatedAt: new Date().toISOString(),
    source:    'fallback',
  }
}

export async function getNielsenSummary(): Promise<NielsenSummary> {
  const now = Date.now()
  if (cache && cache.expiresAt > now) return cache.data

  try {
    const data = await fetchFromS3()
    cache = { data, expiresAt: now + 3_600_000 }
    return data
  } catch {
    return fallbackSummary()
  }
}

export async function getMarketMetrics() {
  const s = await getNielsenSummary()
  return s.market
}

export async function getAudienceTrend(): Promise<TrendPoint[]> {
  const s = await getNielsenSummary()
  return s.trend30d
}
